---
- block:
  - name: Ensure Java dependencies are installed.
    apt: "name={{ item }} state=present update_cache=yes"
    with_items:
      - software-properties-common

  - name: Add ppa:webupd8team/java repository.
    apt_repository:
      repo: "ppa:webupd8team/java"
      state: present
      update_cache: yes

  - name: Accept Java 8 License
    become: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: INSTALL TOOLS
    apt: "name={{item}} state=present update_cache=yes"
    with_items:
       - "{{ Tools }}"
  become: true